data_file = "public/data.json"
public_dir = "public"
qr_dir = "public/qr"

[verifier]
name = "Parity"
public_key = "c46a22b9da19540a77cbde23197e5fd90485c72b4ecf3c599ecca6998f39bd57"

[[chains]]
name = "polkadot"
rpc_endpoint = "wss://rpc.polkadot.io"
color = "#e6007a"

[chains.github_release]
owner = "paritytech"
repo = "polkadot"
genesis_hash = "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3"

[[chains]]
name = "kusama"
rpc_endpoint = "wss://kusama-rpc.polkadot.io"
color = "#000000"

[chains.github_release]
owner = "paritytech"
repo = "polkadot"
genesis_hash = "0xb0a8d493285c2df73290dfb7e61f870f17b41801197a149ca93654499ea3dafe"

[[chains]]
name = "westend"
rpc_endpoint = "wss://westend-rpc.polkadot.io"
color = "#f27230"

[chains.github_release]
owner = "paritytech"
repo = "polkadot"
genesis_hash = "0xe143f23803ac50e8f6f8e62695d1ce9e4e1d68aa36c1cd2cfd15340213f3423e"

# current work
[[chains]]
name = "acala"
rpc_endpoints = [
	'wss://acala-rpc.dwellir.com',
	'wss://acala-rpc-0.aca-api.network',
	'wss://acala-rpc-1.aca-api.network',
	'wss://acala-rpc-2.aca-api.network/ws',
	'wss://acala-rpc-3.aca-api.network/ws',
	'wss://acala.polkawallet.io',
]
color = "#645AFF"

[chains.github_release]
owner = "AcalaNetwork"
repo = "Acala"
genesis_hash = "0xfc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c"
